### ISSUE TITLE
feat: Swaplace LP Header

### ISSUE THREAD

**Issue by FrancoAguzzi** [blockful-io/swaplace-frontend#3]
The goal of this task is to implement the Swaplace LP header component.

This component should be called `LandingPageHeader`

![Image](https://github.com/blockful-io/swaplace/assets/49823133/f29a83f5-e40a-4d36-b22d-fe563987a27b)

CTAs should work as described below:

- Swaplace icon should redirect visitors to /
- "Home" nav item should redirect visitors to /
- "About" nav item should redirect visitors to /about
- "Ecosystem" nav item should redirect visitors to /ecosystem
- "Community" nav item should redirect visitors to "https://discord.gg/aPVhNSR9sS"
- "Incentives" nav item should redirect visitors to "https://discord.gg/m75QtXydZM"
- "Get in touch" CTA should redirect users to "https://t.me/gabrielnvk"

**Comment by heronlancellot** [comment]
#15
