### ISSUE TITLE
style: remove the circular grayish color around the arrow when hovered

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/swaplace-frontend#36]
There is a circular kinda grey mixed in yellow around the arrow when hovered.
![Image](https://github.com/blockful-io/swaplace-frontend/assets/90667119/f2efc79e-ad95-47b1-a724-3d8ea5fbcd6a)

Proposal: It is more appealing to just make the circle disappear, leaving only the arrow during the hover animation.

**Comment by heronlancellot** [comment]
Closed by #58
